from typing import Any, Callable

class SocketIO:
    def __init__(self, *args: Any, **kwargs: Any): ...
    def init_app(self, app: Any, **kwargs: Any) -> None: ...
    def on(self, event: str, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...
    def run(self, app: Any, *args: Any, **kwargs: Any) -> None: ...
